[project]
name = "baby-foot-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "better-profanity==0.7.0",
    "cachelib==0.10.2",
    "certifi==2022.12.7",
    "charset-normalizer==3.1.0",
    "click==8.1.3",
    "contourpy==1.0.7",
    "cycler==0.11.0",
    "dash==2.8.1",
    "dash-bootstrap-components==1.4.1",
    "dash-core-components==2.0.0",
    "dash-html-components==2.0.0",
    "dash-table==5.0.0",
    "et-xmlfile==1.1.0",
    "flask==2.2.2",
    "flask-session==0.4.0",
    "fonttools==4.39.0",
    "gunicorn==20.1.0",
    "idna==3.4",
    "itsdangerous==2.1.2",
    "jinja2==3.1.2",
    "joblib==1.2.0",
    "kiwisolver==1.4.4",
    "markupsafe==2.1.2",
    "matplotlib==3.7.1",
    "nltk==3.8.1",
    "numpy==1.24.2",
    "oauthlib==3.2.2",
    "openpyxl==3.0.10",
    "packaging==23.0",
    "pandas==1.5.3",
    "pillow==9.4.0",
    "plotly==5.13.1",
    "psycopg2==2.9.5",
    "psycopg2-binary==2.9.5",
    "pyparsing==3.0.9",
    "python-dateutil==2.8.2",
    "pytz==2023.3",
    "regex==2022.10.31",
    "requests==2.28.2",
    "requests-oauthlib==1.3.1",
    "six==1.16.0",
    "sqlalchemy==1.4.29",
    "tenacity==8.2.2",
    "textblob==0.17.1",
    "tqdm==4.65.0",
    "urllib3==1.26.15",
    "user-agents==2.2.0",
    "werkzeug==2.2.2",
]
